version: '3.9'
services:
 server:
    build: ./server
    container_name: gql-server
    ports:
      - "4000:4000"
    networks:
      - nuxt-network

 frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
    networks:
      - nuxt-network
     
 web-server:
     image: nginx:1.17.10-alpine
     container_name: web-server
     volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       - web-root:/var/www/html
       - ./nginx/logs:/var/log/nginx
     ports:
       - "80:80"
     networks:
       nuxt-network:
     depends_on:
       - frontend
     restart: unless-stopped

 uploader:
    build: ./file-uploader
    container_name: uploader
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - nuxt-network

volumes:
 web-root:
 
networks:
  nuxt-network:
    driver: bridge
